services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mobicoop\Bundle\MobicoopBundle\Controller\DefaultController:
    arguments:
      $searchComponentHorizontal: "%env(bool:CARPOOL_SEARCH_HORIZONTAL)%"
